version: "3"

services:
  gpt:
    build: .
    container_name: gpt
    ports:
      - '80:80'
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=gpt.settings
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    depends_on:
      - db

  db:
    container_name: 'db'
    image: mysql:8
    environment:
      MYSQL_USER: $SQL_USER
      MYSQL_DATABASE: $SQL_DATABASE
      MYSQL_PASSWORD: $SQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $SQL_PASSWORD
    volumes:
      - 'db:/var/lib/mysql'
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

volumes:
  db: