version: "3"

services:
  gpt:
    build: gpt 
    ports: 
      - '80:80'
    env_file:
      - .env

  mysql-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: ${MYSQL_DB_DATABASE}
      MYSQL_USER: ${MYSQL_DB_USER}
      MYSQL_PASSWORD: ${MYSQL_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_DB_ROOT_PASSWORD}
    ports:
      - '${MYSQL_PORT}:3306'
    expose:
      - '${MYSQL_PORT}'
    volumes:
      - mysql_db:/var/lib/mysql
volumes:
  mysql_db:
    driver: local