# Generated by Django 4.2.1 on 2023-06-04 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GPTModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, unique=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('prompt_token_cost', models.FloatField()),
                ('completition_token_cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_text', models.TextField()),
                ('prompt_token_count', models.IntegerField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_evaluated', models.BooleanField(default=False)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gpt.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationIteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_started', models.BooleanField(default=False)),
                ('is_finished', models.BooleanField(default=False)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gpt.api')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gpt.dataset')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gpt.gptmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Completition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completition_id', models.CharField(max_length=100, unique=True)),
                ('completition_text', models.TextField()),
                ('completition_token_count', models.IntegerField()),
                ('evaluation_iteration', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gpt.evaluationiteration')),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gpt.prompt')),
            ],
        ),
    ]
