# Generated by Django 4.2.1 on 2023-06-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='completition',
            name='completition_error_text',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='completition',
            name='completition_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='completition',
            name='completition_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='completition',
            name='completition_token_count',
            field=models.IntegerField(null=True),
        ),
    ]
