# Generated by Django 4.2.1 on 2023-06-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt', '0002_completition_completition_error_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completition',
            old_name='completition_error_text',
            new_name='error_text',
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='is_evaluated',
        ),
        migrations.AddField(
            model_name='completition',
            name='is_error',
            field=models.BooleanField(default=False),
        ),
    ]
