# Generated by Django 4.2.1 on 2023-06-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt', '0003_rename_completition_error_text_completition_error_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='name',
            field=models.CharField(default='main', max_length=100),
        ),
    ]
