# Generated by Django 4.2.1 on 2023-06-04 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt', '0004_api_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='prompt_token_count',
        ),
        migrations.AddField(
            model_name='completition',
            name='prompt_token_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
