# Generated by Django 4.2.1 on 2023-06-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt', '0005_remove_prompt_prompt_token_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completition',
            name='error_text',
            field=models.TextField(null=True),
        ),
    ]
