# Generated by Django 4.2.1 on 2023-06-07 12:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt', '0006_alter_completition_error_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='gptmodel',
            name='p_best_of',
            field=models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Best of'),
        ),
        migrations.AddField(
            model_name='gptmodel',
            name='p_frequency_penalty',
            field=models.FloatField(default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='Frequency penalty'),
        ),
        migrations.AddField(
            model_name='gptmodel',
            name='p_max_length',
            field=models.BigIntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)], verbose_name='Response max length (tokens)'),
        ),
        migrations.AddField(
            model_name='gptmodel',
            name='p_stop_sequences',
            field=models.TextField(default=None, help_text='Each sequence on a new line', null=True, verbose_name='Stop sequence'),
        ),
        migrations.AddField(
            model_name='gptmodel',
            name='p_temperature',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='Temperature'),
        ),
        migrations.AddField(
            model_name='gptmodel',
            name='p_top_p',
            field=models.FloatField(default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Top P'),
        ),
        migrations.AddField(
            model_name='prompt',
            name='prompt_key',
            field=models.CharField(default=None, max_length=200, null=True, verbose_name='Prompt identifier'),
        ),
    ]
