# Generated by Django 4.2.1 on 2023-06-07 12:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt', '0007_gptmodel_p_best_of_gptmodel_p_frequency_penalty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gptmodel',
            name='p_best_of',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Best of'),
        ),
        migrations.AlterField(
            model_name='gptmodel',
            name='p_frequency_penalty',
            field=models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='Frequency penalty'),
        ),
        migrations.AlterField(
            model_name='gptmodel',
            name='p_max_length',
            field=models.BigIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)], verbose_name='Response max length (tokens)'),
        ),
        migrations.AlterField(
            model_name='gptmodel',
            name='p_stop_sequences',
            field=models.TextField(blank=True, default=None, help_text='Each sequence on a new line', null=True, verbose_name='Stop sequence'),
        ),
        migrations.AlterField(
            model_name='gptmodel',
            name='p_top_p',
            field=models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Top P'),
        ),
    ]
