# Generated by Django 4.2.1 on 2023-06-07 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt', '0008_alter_gptmodel_p_best_of_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gptmodel',
            name='p_temperature',
            field=models.FloatField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='Temperature'),
        ),
    ]
