# Generated by Django 4.2.1 on 2023-06-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt', '0010_gptmodel_p_presence_penalty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gptmodel',
            name='model',
            field=models.CharField(choices=[('text-davinci-003', 'text-davinci-003'), ('text-davinci-002', 'text-davinci-002'), ('text-curie-001', 'text-curie-001'), ('text-babbage-001', 'text-babbage-001'), ('text-ada-001', 'text-ada-001')], max_length=100, unique=True),
        ),
    ]
