# Generated by Django 4.2.1 on 2023-06-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt', '0011_alter_gptmodel_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completition',
            name='completition_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='completition',
            name='error_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gptmodel',
            name='model',
            field=models.CharField(choices=[('text-davinci-003', 'text-davinci-003'), ('text-davinci-002', 'text-davinci-002'), ('text-curie-001', 'text-curie-001'), ('text-babbage-001', 'text-babbage-001'), ('text-ada-001', 'text-ada-001'), ('gpt-3.5-turbo', 'gpt-3.5-turbo'), ('gpt-3.5-turbo-0301', 'gpt-3.5-turbo-0301')], max_length=100, unique=True),
        ),
    ]
